### ISSUE TITLE
 Encountering "Unknown method 'eth_signTypedData_v4' error" with ethers Adapter Signer while using Wagmi WalletConnect for Signin SignTypedData

### ISSUE THREAD

**Issue by ManavPanchal** [wevm/wagmi#3626]
I've run into a bit of a snag while trying to sign Typed Data using the signer.signTypedData method from the ethers adapter. I'm using Wagmi to connect Trust Wallet via Wallet Connect. The issue is that I keep getting errors, and they're not very friendly. The errors I'm facing is 

>
```
Uncaught (in promise) Error: could not coalesce error (error={ "code": 5201, "message": "Unknown method(s) requested" }, payload={ "id": 2, "jsonrpc": "2.0", "method": "eth_signTypedData_v4"...)
```
>

Surprisingly, switching to signTypedDataAsync from the useSignTypedData hook resolves the issue, allowing smooth signing with no errors encountered.

**Wagmi config:**

```
const { chains, publicClient, webSocketPublicClient } = configureChains(
  [mainnet, optimism],
  [publicProvider()],
);

export const config = createConfig({
  autoConnect: true,
  chains,
  connectors: [
    new WalletConnectConnector({
      chains,
      options: {
        projectId: process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID,
      },
    }),
  ],
  publicClient,
  webSocketPublicClient,
});

```
**Code snippet for Ethers Adapter:**

```
export function walletClientToSigner(walletClient, connectedNetwork) {
  const { account, chain, transport } = walletClient;
  const network = {
    chainId: chain?.id || connectedNetwork?.id,
    name: chain?.name || connectedNetwork?.name,
    ensAddress:
      chain?.contracts?.ensRegistry?.address ||
      connectedNetwork?.contracts?.ensRegistry?.address,
  };
  const provider = new BrowserProvider(transport, network);
  const signer = new JsonRpcSigner(provider, account?.address);
  return signer;
}

export function useSigner(chainId) {
  const { chain } = useNetwork();
  const { data: walletClient } = useWalletClient({
    chainId: chainId || chain?.id,
  });
  const [signer, setSigner] = useState(null);

  useEffect(() => {
    if (walletClient) setSigner(walletClientToSigner(walletClient, chain));
  }, [walletClient]);

  return signer;
}
```
**Snippet for sending sign request**

```
const signer = useSigner();
await signer.signTypedData(domain,types,value);
```

Seems like this issue is happening in the interaction between the ethers adapter signer and Trust Wallet Connect.

### Link to Minimal Reproducible Example

https://wagmi-with-wallet-connect.vercel.app/

### Steps To Reproduce

1. Configure Wagmi with the same settings.
2. Obtain the signer from the Ethers adapter.
3. Attempt to execute signer.signTypedData().
4. Observe the encountered error.

Alternatively, you can visit my public repository [here](https://github.com/ManavPanchal/Wagmi-with-WalletConnect.git) and connect your Trust Wallet. Try clicking on the "signTypedData: with ethers adapter" button to reproduce the error.

### Wagmi Version

^1.3.10

### Ethers Version

^6.11.1

**Comment by philwalkers** [comment]
I am also running into a similar issue with Trust Wallet extension. I cannot sign typed data using the signTypedData function.
This was working perfectly fine few days ago. 

```
UnknownRpcError: An unknown RPC error occurred.

Details: Unexpected non-whitespace character after JSON at position 1 (line 1 column 2)
Version: viem@1.21.3
    at delay.count.count (buildRequest.js:101:27)
    at async attemptRetry (withRetry.js:17:30)
```

**Comment by glitch-txs** [comment]
this was fixed already, you're using an old version of the WalletConnect connector

**Comment by ManavPanchal** [comment]
@glitch-txs, Thank you for the response. I appreciate your assistance. Could you kindly specify the recommended or fixed version of the WalletConnect connector that addresses this issue? Currently, I'm using a WalletConnect connector derived from the Wagmi/connector, as indicated in the title. I want to ensure I have the most up-to-date and stable version.

**Comment by glitch-txs** [comment]
Wagmi v2 latest

**Comment by ManavPanchal** [comment]
@glitch-txs, Thank you for the quick reply ! I've updated my project to Wagmi v2 as suggested, but unfortunately, I'm still facing the same issue with the signer.signTypedData method and getting the same error.

You can checkout the deployment for the same: [Demo Deployment](https://wagmi-with-wallet-connect-git-wagmi-v2-manav-panchal.vercel.app/?_vercel_share=MdiLCJfpd6hHLXwCWPtHfG46PBg6zEca).

You can also find the related code in my repo: [Wagmi-with-WalletConnect](https://github.com/ManavPanchal/Wagmi-with-WalletConnect/tree/wagmi-v2).

**Comment by glitch-txs** [comment]
@ManavPanchal your lock file is outdated. You also don't need @wagmi/core if you have Wagmi installed. 
Delete node_modules and package-lock and reinstall

**Comment by ManavPanchal** [comment]
@glitch-txs thank you for your guidance! I truly appreciate the developer-level suggestions. I had already made the changes you suggested, including updating the lock file. However, it seems I missed pushing the updated package-lock.json file.

I have now corrected that oversight and ensured that everything is up-to-date. But unfortunately, the issue still persists. 

[demo](https://wagmi-with-wallet-connect-git-wagmi-v2-manav-panchals-projects.vercel.app?_vercel_share=H9pKnOj0jYTYKUhkWTPjD2dRUAzw0Y8W),  [repo](https://github.com/ManavPanchal/Wagmi-with-WalletConnect/tree/wagmi-v2).

**Comment by glitch-txs** [comment]
@ManavPanchal thanks for the MRE, I was able to repro, seems an issue with WalletConnect <> Ethers v6 compat, I'll message Richard

So far I'm not able to sign a valid message: https://github.com/glitch-txs/ethers-ethereum-provider
Feel free to open an issue in the ethers repo
